name=ESP32IoTSDK
version=0.1.2
author=Vishal
maintainer=Vishal
sentence=Reusable IoT SDK for ESP32 with WiFi, MQTT, OTA and provisioning support.
paragraph=ESP32 IoT SDK providing reusable components for WiFi management, NVS storage, MQTT communication, OTA updates and WiFi provisioning.
category=Communication
url=https://github.com/vishal-95-um/esp32-iot-management
architectures=esp32
depends=PubSubClient